language: scala
jdk: openjdk11

before_script:
  - cd website && yarn install --frozen-lockfile

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmt/test test:scalafmt/test sbt:scalafmt/test
  - sbt ++$TRAVIS_SCALA_VERSION test
